services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - DATABASE_URL=redis://db:6379
      - LISTEN_PORT=80
      - LOG_LEVEL=${LOG_LEVEL:-3}
    ports:
      - 127.0.0.1:44388:80
    restart: always

  bot:
    build:
      context: ./apps/bot
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - DATABASE_URL=redis://db:6379
      - EXPIRATION=${EXPIRATION:-3600}
      - FETCH_INTERVAL=${FETCH_INTERVAL:-1800}
      - GITHUB_TOKEN=${GITHUB_TOKEN:?error}
      - LOG_LEVEL=${LOG_LEVEL:-3}
    restart: always

  db:
    image: redis/redis-stack-server:7.4.0-v0
    volumes:
      - db:/data
    restart: always

volumes:
  db:
